version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: almasdar-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo-data:/data/db

  # (backend/frontend can stay as-is; we’ll start Mongo alone first)

volumes:
  mongo-data:
