
import { Injectable, signal, effect, PLATFORM_ID, inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export type Language = 'ar' | 'en';

export interface Translations {
  [key: string]: string | Translations;
}

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private platformId = inject(PLATFORM_ID);

  // Reactive language state (Arabic default)
  currentLanguage = signal<Language>('ar');

  // Translations storage
  private translations: Record<Language, Translations> = { ar: {}, en: {} };

  constructor() {
    // Always load translations first
    this.loadTranslations();
    
    if (isPlatformBrowser(this.platformId)) {
      this.initializeLanguage();
      // Update DOM attrs when language changes
      effect(() => {
        this.applyLanguage(this.currentLanguage());
      });
    } else {
      // For SSR, set default language
      this.currentLanguage.set('ar');
    }
  }

  private initializeLanguage(): void {
    const savedLang = (isPlatformBrowser(this.platformId)
      ? (localStorage.getItem('language') as Language | null)
      : null);

    if (savedLang === 'ar' || savedLang === 'en') {
      this.currentLanguage.set(savedLang);
    } else {
      this.currentLanguage.set('ar');
    }
  }

  private applyLanguage(lang: Language): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const html = document.documentElement;
    html.setAttribute('lang', lang);
    html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    localStorage.setItem('language', lang);
  }

  private loadTranslations(): void {
    // Arabic
    this.translations.ar = {
      common: {
        loading: 'جارٍ التحميل',
        required: 'مطلوب',
        error: 'حدث خطأ',
        success: 'نجح',
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        close: 'إغلاق',
        confirm: 'تأكيد',
        yes: 'نعم',
        no: 'لا',
        search: 'بحث',
        next: 'التالي',
        previous: 'السابق',
        optional: 'اختياري',
        and: 'و',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور'
      },
      nav: {
        products: 'المنتجات',
        categories: 'الفئات',
        admin: 'لوحة التحكم',
        account: 'حسابي',
        wishlist: 'المفضلة',
        cart: 'السلة',
        login: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',
        dashboard: 'لوحة المعلومات',
        myOrders: 'طلباتي',
        profile: 'الملف الشخصي',
        addresses: 'العناوين',
        adminPanel: 'لوحة الإدارة',
        searchPlaceholder: 'ابحث عن كاميرات، أنظمة الأمان، الإنذارات...'
      },
      admin: {
        dashboardTitle: 'لوحة تحكم الإدارة',
        dashboardSubtitle: 'إدارة الموقع، المنتجات، المستخدمين، الطلبات والمزيد',
        overview: 'نظرة عامة',
        manageUsers: 'إدارة المستخدمين',
        manageProducts: 'إدارة المنتجات',
        manageCategories: 'إدارة الفئات',
        manageOrders: 'إدارة الطلبات',
        manageBanners: 'إدارة البنرات',
        loginTitle: 'تسجيل دخول الإدارة',
        loginButton: 'تسجيل الدخول',
        // Stats
        totalUsers: 'إجمالي المستخدمين',
        totalProducts: 'إجمالي المنتجات',
        totalOrders: 'إجمالي الطلبات',
        totalRevenue: 'إجمالي الإيرادات',
        pendingOrders: 'الطلبات المعلقة',
        lowStockProducts: 'منتجات مخزون منخفض',
        // Users
        users: 'المستخدمين',
        user: 'مستخدم',
        email: 'البريد الإلكتروني',
        name: 'الاسم',
        role: 'الدور',
        status: 'الحالة',
        actions: 'الإجراءات',
        active: 'نشط',
        inactive: 'غير نشط',
        admin: 'مدير',
        staff: 'موظف',
        customerRole: 'عميل',
        allRoles: 'كل الأدوار',
        anyStatus: 'أي حالة',
        filter: 'تصفية',
        searchUsers: 'البحث عن المستخدمين...',
        deleteUser: 'حذف المستخدم',
        deleteUserConfirm: 'هل أنت متأكد من حذف هذا المستخدم؟',
        userDeleted: 'تم حذف المستخدم بنجاح',
        userUpdated: 'تم تحديث المستخدم بنجاح',
        // Categories
        categories: 'الفئات',
        category: 'فئة',
        addCategory: 'إضافة فئة',
        editCategory: 'تعديل الفئة',
        categoryName: 'اسم الفئة',
        categorySlug: 'الرابط',
        parentCategory: 'الفئة الأصلية',
        noParent: 'لا يوجد (فئة رئيسية)',
        icon: 'الأيقونة',
        image: 'الصورة',
        sortOrder: 'ترتيب العرض',
        isActive: 'نشط',
        saveCategory: 'حفظ الفئة',
        categoryAdded: 'تمت إضافة الفئة بنجاح',
        categoryUpdated: 'تم تحديث الفئة بنجاح',
        categoryDeleted: 'تم حذف الفئة بنجاح',
        deleteCategoryConfirm: 'هل أنت متأكد من حذف هذه الفئة؟',
        // Banners
        banners: 'البنرات',
        banner: 'بنر',
        addBanner: 'إضافة بنر',
        editBanner: 'تعديل البنر',
        title: 'العنوان',
        imageUrl: 'رابط الصورة',
        linkUrl: 'رابط الوجهة',
        position: 'الموقع',
        hero: 'بنر رئيسي',
        sidebar: 'شريط جانبي',
        footer: 'تذييل',
        startDate: 'تاريخ البدء',
        endDate: 'تاريخ الانتهاء',
        saveBanner: 'حفظ البنر',
        bannerAdded: 'تمت إضافة البنر بنجاح',
        bannerUpdated: 'تم تحديث البنر بنجاح',
        bannerDeleted: 'تم حذف البنر بنجاح',
        deleteBannerConfirm: 'هل أنت متأكد من حذف هذا البنر؟',
        filterByPosition: 'تصفية حسب الموقع',
        allPositions: 'كل المواقع',
        // Products
        products: 'المنتجات',
        product: 'منتج',
        addProduct: 'إضافة منتج',
        editProduct: 'تعديل المنتج',
        productName: 'اسم المنتج',
        description: 'الوصف',
        price: 'السعر',
        comparePrice: 'سعر المقارنة',
        cost: 'التكلفة',
        sku: 'رمز المنتج',
        stock: 'المخزون',
        lowStockThreshold: 'حد المخزون المنخفض',
        images: 'الصور',
        specifications: 'المواصفات',
        features: 'الميزات',
        saveProduct: 'حفظ المنتج',
        productAdded: 'تمت إضافة المنتج بنجاح',
        productUpdated: 'تم تحديث المنتج بنجاح',
        productDeleted: 'تم حذف المنتج بنجاح',
        deleteProductConfirm: 'هل أنت متأكد من حذف هذا المنتج؟',
        // Orders
        orders: 'الطلبات',
        order: 'طلب',
        orderNumber: 'رقم الطلب',
        orderDate: 'تاريخ الطلب',
        customer: 'العميل',
        items: 'العناصر',
        total: 'الإجمالي',
        paymentStatus: 'حالة الدفع',
        orderStatus: 'حالة الطلب',
        pending: 'معلق',
        confirmed: 'مؤكد',
        processing: 'قيد المعالجة',
        shipped: 'تم الشحن',
        delivered: 'تم التسليم',
        cancelled: 'ملغي',
        paid: 'مدفوع',
        unpaid: 'غير مدفوع',
        refunded: 'مسترد',
        updateStatus: 'تحديث الحالة',
        orderUpdated: 'تم تحديث الطلب بنجاح',
        viewOrder: 'عرض الطلب',
        searchOrders: 'البحث في الطلبات...',
        filterByStatus: 'تصفية حسب الحالة',
        allStatuses: 'كل الحالات',
        // Sales & Customers
        sales: 'المبيعات',
        sale: 'عملية بيع',
        salesLedger: 'دفتر المبيعات',
        newSale: 'عملية بيع جديدة',
        addSale: 'إضافة عملية بيع',
        salesHistory: 'سجل المبيعات',
        customers: 'الزبائن',
        customerName: 'اسم الزبون',
        customerPhone: 'رقم الهاتف',
        customerEmail: 'البريد الإلكتروني',
        searchCustomer: 'البحث عن زبون...',
        newCustomer: 'زبون جديد',
        selectCustomer: 'اختر الزبون',
        serialNumber: 'الرقم التسلسلي',
        searchBySerial: 'البحث بالرقم التسلسلي...',
        productNotFound: 'المنتج غير موجود',
        addNewProduct: 'إضافة منتج جديد',
        quantity: 'الكمية',
        addItem: 'إضافة منتج',
        removeItem: 'إزالة المنتج',
        saleItems: 'منتجات البيع',
        totalAmount: 'المبلغ الإجمالي',
        paidAmount: 'المبلغ المدفوع',
        remainingAmount: 'المبلغ المتبقي',
        payments: 'الدفعات',
        addPayment: 'إضافة دفعة',
        paymentAmount: 'مبلغ الدفعة',
        paymentDate: 'تاريخ الدفع',
        paymentMethod: 'طريقة الدفع',
        cash: 'نقداً',
        card: 'بطاقة',
        bank: 'تحويل بنكي',
        returnItem: 'إرجاع منتج',
        returned: 'مُرجَع',
        returnDate: 'تاريخ الإرجاع',
        returnReason: 'سبب الإرجاع',
        uploadImages: 'رفع الصور',
        saleDate: 'تاريخ البيع',
        partial: 'دفع جزئي',
        saveSale: 'حفظ العملية',
        saleCreated: 'تم إنشاء عملية البيع بنجاح',
        saleUpdated: 'تم تحديث عملية البيع بنجاح',
        saleDeleted: 'تم حذف عملية البيع بنجاح',
        deleteSaleConfirm: 'هل أنت متأكد من حذف عملية البيع هذه؟',
        searchSales: 'البحث في المبيعات...',
        salesHistoryDesc: 'عرض وإدارة جميع عمليات البيع',
        all: 'الكل',
        paidStatus: 'مدفوع',
        partialStatus: 'جزئي',
        pendingStatus: 'معلق',
        totalSales: 'إجمالي المبيعات',
        totalPaid: 'إجمالي المدفوع',
        totalRemaining: 'إجمالي المتبقي',
        noSalesFound: 'لا توجد مبيعات',
        loadingSales: 'جارٍ تحميل المبيعات...',
        saleDetails: 'تفاصيل البيع',
        customerInfo: 'معلومات الزبون',
        phone: 'الهاتف',
        date: 'التاريخ',
        noPaymentsYet: 'لا توجد دفعات بعد',
        paymentFailed: 'فشل إضافة الدفعة',
        returnFailed: 'فشل إرجاع المنتج',
        bankTransfer: 'تحويل بنكي',
        // Common
        search: 'بحث',
        add: 'إضافة',
        edit: 'تعديل',
        delete: 'حذف',
        save: 'حفظ',
        cancel: 'إلغاء',
        close: 'إغلاق',
        loading: 'جارٍ التحميل...',
        noData: 'لا توجد بيانات',
        error: 'حدث خطأ',
        success: 'نجح',
        confirm: 'تأكيد',
        back: 'رجوع'
      },
      home: {
        heroTitle: 'احمِ ما يهمك',
        heroSubtitle: 'حلول أمنية متقدمة',
        heroDescription: 'أنظمة أمان احترافية للمنازل والشركات. مراقبة على مدار الساعة، تكامل ذكي، وتركيب احترافي.',
        shopNow: 'تسوق الآن',
        getQuote: 'احصل على عرض سعر',
        happyCustomers: 'عميل سعيد',
        uptime: 'وقت التشغيل',
        yearsExperience: 'سنة خبرة',
        browseByCategory: 'تصفح حسب الفئة',
        categoriesDescription: 'استكشف مجموعتنا الشاملة من منتجات الأمان',
        feature1Title: 'أمان على مدار الساعة',
        feature1Desc: 'حماية دائمة لممتلكاتك',
        feature2Title: 'دعم احترافي',
        feature2Desc: 'تركيب وصيانة احترافية',
        feature3Title: 'جودة ممتازة',
        feature3Desc: 'منتجات أمان رائدة في الصناعة',
        feature4Title: 'توصيل سريع',
        feature4Desc: 'شحن سريع وآمن في جميع أنحاء البلاد',
        featuredProducts: 'المنتجات المميزة',
        featuredDescription: 'حلول أمان عالية التقييم يثق بها الآلاف',
        viewAllProducts: 'عرض جميع المنتجات',
        ctaTitle: 'هل تحتاج مساعدة في اختيار نظام الأمان المناسب؟',
        ctaDescription: 'خبراؤنا في الأمان هنا لمساعدتك في إيجاد الحل المثالي لاحتياجاتك.',
        talkToExpert: 'تحدث إلى خبير',
        callNow: 'اتصل الآن'
      },
      products: {
        title: 'منتجات الأمان',
        subtitle: 'أنظمة ومعدات أمان احترافية',
        searchPlaceholder: 'البحث عن المنتجات...',
        filters: 'التصفية',
        clearAll: 'مسح الكل',
        clearFilters: 'مسح الفلاتر',
        category: 'الفئة',
        allCategories: 'كل الفئات',
        priceRange: 'نطاق السعر',
        min: 'الحد الأدنى',
        max: 'الحد الأقصى',
        availability: 'التوفر',
        allProducts: 'جميع المنتجات',
        inStock: 'متوفر',
        inStockLabel: 'في المخزون',
        outOfStock: 'غير متوفر',
        lowStock: 'مخزون منخفض',
        quickView: 'عرض سريع',
        addToCart: 'أضف للسلة',
        productsFound: 'منتج موجود',
        page: 'صفحة',
        of: 'من',
        noProductsFound: 'لم يتم العثور على منتجات',
        tryAdjusting: 'حاول تعديل المرشحات أو مصطلحات البحث'
      },
      account: {
        welcome: 'مرحباً',
        totalOrders: 'إجمالي الطلبات',
        pendingOrders: 'الطلبات المعلقة',
        wishlistItems: 'المنتجات المفضلة',
        savedAddresses: 'العناوين المحفوظة',
        recentOrders: 'الطلبات الأخيرة',
        viewAll: 'عرض الكل',
        orderNumber: 'رقم الطلب',
        date: 'التاريخ',
        status: 'الحالة',
        total: 'الإجمالي',
        viewDetails: 'عرض التفاصيل'
      },
      categoriesPage: {
        title: 'فئات المنتجات',
        subtitle: 'استكشف مجموعتنا الشاملة من حلول الأمان',
        categoriesLabel: 'فئات',
        productsLabel: 'منتجات',
        loadingCategories: 'جارٍ تحميل الفئات',
        exploreProducts: 'استكشف المنتجات',
        needHelp: 'هل تحتاج مساعدة في الاختيار؟',
        helpDescription: 'خبراء الأمان لدينا هنا لمساعدتك في العثور على الحل المثالي لاحتياجاتك',
        contactUs: 'اتصل بنا',
        requestQuote: 'طلب عرض سعر'
      },
      footer: {
        brandDescription: 'شريكك الموثوق في حلول الأمان المتقدمة. حماية ما يهمك أكثر بتقنية متطورة وخدمة موثوقة.',
        company: 'الشركة',
        aboutUs: 'من نحن',
        careers: 'الوظائف',
        blog: 'المدونة',
        pressKit: 'المواد الصحفية',
        support: 'الدعم',
        helpCenter: 'مركز المساعدة',
        contactUs: 'اتصل بنا',
        faq: 'الأسئلة الشائعة',
        shipping: 'الشحن',
        returns: 'المرتجعات',
        legal: 'قانوني',
        privacyPolicy: 'سياسة الخصوصية',
        termsOfService: 'شروط الخدمة',
        cookiePolicy: 'سياسة ملفات تعريف الارتباط',
        newsletter: 'اشترك في النشرة الإخبارية',
        newsletterDesc: 'احصل على آخر التحديثات حول منتجات الأمان والعروض الحصرية.',
        emailPlaceholder: 'أدخل عنوان بريدك الإلكتروني',
        subscribe: 'اشترك',
        allRightsReserved: 'جميع الحقوق محفوظة.',
        weAccept: 'نقبل:'
      },
      login: {
        welcomeBack: 'مرحباً بعودتك',
        signInSubtitle: 'سجل الدخول إلى حسابك للمتابعة',
        professionalSystems: 'أنظمة احترافية',
        monitoring247: 'مراقبة على مدار الساعة',
        expertInstallation: 'تركيب احترافي',
        email: 'البريد الإلكتروني',
        emailPlaceholder: 'أدخل بريدك الإلكتروني',
        emailRequired: 'البريد الإلكتروني مطلوب',
        emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
        password: 'كلمة المرور',
        passwordPlaceholder: 'أدخل كلمة المرور',
        passwordRequired: 'كلمة المرور مطلوبة',
        passwordMinLength: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
        rememberMe: 'تذكرني',
        forgotPassword: 'نسيت كلمة المرور؟',
        signIn: 'تسجيل الدخول',
        signingIn: 'جارٍ تسجيل الدخول...',
        or: 'أو',
        continueWithGoogle: 'المتابعة مع Google',
        continueWithFacebook: 'المتابعة مع Facebook',
        continueWithApple: 'المتابعة مع Apple',
        noAccount: 'ليس لديك حساب؟',
        createAccount: 'إنشاء حساب'
      },
      register: {
        createAccount: 'إنشاء حساب',
        createAccountSubtitle: 'أنشئ حسابك وابدأ في تأمين ما يهمك',
        joinThousands: 'انضم إلى آلاف العملاء الذين يثقون بنا',
        firstName: 'الاسم الأول',
        firstNamePlaceholder: 'أدخل اسمك الأول',
        firstNameRequired: 'الاسم الأول مطلوب',
        nameMinLength: 'على الأقل حرفان',
        lastName: 'الاسم الأخير',
        lastNamePlaceholder: 'أدخل اسمك الأخير',
        lastNameRequired: 'الاسم الأخير مطلوب',
        phoneNumber: 'رقم الهاتف',
        phonePlaceholder: 'أدخل رقم هاتفك',
        phoneInvalid: 'يرجى إدخال رقم هاتف صحيح',
        company: 'الشركة',
        companyPlaceholder: 'اسم شركتك',
        confirmPassword: 'تأكيد كلمة المرور',
        confirmPasswordPlaceholder: 'أعد إدخال كلمة المرور',
        confirmPasswordRequired: 'تأكيد كلمة المرور مطلوب',
        passwordMismatch: 'كلمات المرور غير متطابقة',
        agreeToTerms: 'أوافق على',
        termsConditions: 'الشروط والأحكام',
        privacyPolicy: 'سياسة الخصوصية',
        termsRequired: 'يجب الموافقة على الشروط والأحكام',
        creatingAccount: 'جارٍ إنشاء الحساب...',
        alreadyHaveAccount: 'هل لديك حساب بالفعل؟'
      },
      accountDash: {
        myAccount: 'حسابي',
        overview: 'نظرة عامة',
        orders: 'الطلبات',
        addresses: 'العناوين',
        profile: 'الملف الشخصي',
        viewAll: 'عرض الكل',
        manage: 'إدارة',
        viewAllOrders: 'عرض جميع الطلبات',
        recentOrders: 'الطلبات الأخيرة',
        noOrders: 'لا توجد طلبات بعد',
        startShopping: 'ابدأ التسوق',
        order: 'طلب',
        items: 'عناصر',
        view: 'عرض',
        quickActions: 'إجراءات سريعة',
        updateProfile: 'تحديث الملف الشخصي',
        manageAddresses: 'إدارة العناوين',
        orderHistory: 'سجل الطلبات',
        accountSettings: 'إعدادات الحساب'
      },
      accountProfile: {
        profile: 'الملف الشخصي',
        subtitle: 'إدارة معلومات حسابك وإعدادات الأمان',
        personalInfo: 'المعلومات الشخصية',
        updatePersonalInfo: 'تحديث معلوماتك الشخصية',
        securitySettings: 'إعدادات الأمان',
        updatePasswordDesc: 'تحديث كلمة المرور الخاصة بك',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        changePassword: 'تغيير كلمة المرور',
        updating: 'جارٍ التحديث...',
        saveChanges: 'حفظ التغييرات',
        cancel: 'إلغاء'
      },
      accountOrders: {
        title: 'طلباتي',
        subtitle: 'تتبع وأدر سجل طلباتك',
        status: 'الحالة',
        dateRange: 'النطاق الزمني',
        allOrders: 'جميع الطلبات',
        pending: 'معلق',
        confirmed: 'مؤكد',
        shipped: 'تم الشحن',
        delivered: 'تم التسليم',
        cancelled: 'ملغي',
        allTime: 'كل الوقت',
        last30Days: 'آخر 30 يومًا',
        last90Days: 'آخر 90 يومًا',
        thisYear: 'هذه السنة',
        search: 'بحث',
        searchPlaceholder: 'رقم الطلب، الحالة، التتبع...',
        loading: 'جارٍ تحميل الطلبات...',
        orderId: 'رقم الطلب',
        date: 'التاريخ',
        items: 'العناصر',
        total: 'الإجمالي',
        statusLabel: 'الحالة',
        payment: 'الدفع',
        actions: 'الإجراءات',
        view: 'عرض',
        noOrdersFound: 'لم يتم العثور على طلبات',
        tryAdjustFilters: 'جرّب تعديل عوامل التصفية',
        noOrdersYet: 'لم تقم بأي طلبات حتى الآن',
        startShopping: 'ابدأ التسوق',
        details: 'تفاصيل الطلب',
        paymentStatus: 'حالة الدفع',
        tracking: 'التتبع',
        itemsHeader: 'العناصر',
        shippingAddress: 'عنوان الشحن',
        orderSummary: 'ملخص الطلب',
        subtotal: 'المجموع الفرعي',
        shipping: 'الشحن',
        tax: 'الضريبة',
        totalLabel: 'الإجمالي',
        notes: 'ملاحظات',
        qty: 'الكمية'
      },
      accountAddresses: {
        title: 'عناوين الشحن',
        subtitle: 'إدارة عناوينك المحفوظة لتسريع الدفع',
        addNewAddress: 'إضافة عنوان جديد',
        loading: 'جارٍ تحميل العناوين...',
        editAddress: 'تعديل العنوان',
        fullName: 'الاسم الكامل',
        phoneNumber: 'رقم الهاتف',
        streetAddress: 'عنوان الشارع',
        apartment: 'الشقة، المبنى... (اختياري)',
        city: 'المدينة',
        state: 'الولاية / المحافظة',
        postalCode: 'الرمز البريدي',
        country: 'الدولة',
        setAsDefault: 'تعيين كافتراضي',
        isDefault: 'افتراضي',
        noAddressesSaved: 'لا توجد عناوين محفوظة',
        addAddressCta: 'أضف عنوانك الأول للبدء',
        addAddress: 'إضافة عنوان',
        saveAddress: 'حفظ العنوان',
        updateAddress: 'تحديث العنوان',
        saving: 'جارٍ الحفظ...',
        cancel: 'إلغاء',
        defaultUpdated: 'تم تحديث العنوان الافتراضي!',
        deleteConfirm: 'هل أنت متأكد من حذف هذا العنوان؟',
        deleteSuccess: 'تم حذف العنوان بنجاح!',
        addSuccess: 'تمت إضافة العنوان بنجاح!',
        updateSuccess: 'تم تحديث العنوان بنجاح!',
        loadError: 'فشل تحميل العناوين',
        updateError: 'فشل تحديث العنوان',
        addError: 'فشل إضافة العنوان',
        deleteError: 'فشل حذف العنوان'
      },
      checkout: {
        title: 'الدفع',
        subtitle: 'دفع آمن في ثلاث خطوات بسيطة',
        step1: 'الشحن',
        step2: 'الدفع',
        step3: 'المراجعة',
        shippingInformation: 'معلومات الشحن',
        fullName: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        phone: 'الهاتف',
        address1: 'العنوان 1',
        address2: 'العنوان 2',
        city: 'المدينة',
        state: 'الولاية',
        zip: 'الرمز البريدي',
        country: 'الدولة',
        continueToPayment: 'المتابعة إلى الدفع',
        payment: 'الدفع',
        methodCard: 'بطاقة ائتمان/خصم',
        methodCOD: 'الدفع عند الاستلام',
        cardNumber: 'رقم البطاقة',
        nameOnCard: 'الاسم على البطاقة',
        expiry: 'تاريخ الانتهاء',
        cvc: 'CVC',
        back: 'رجوع',
        reviewOrder: 'مراجعة الطلب',
        reviewYourOrder: 'راجع طلبك',
        orderSummary: 'ملخص الطلب',
        items: 'العناصر',
        subtotal: 'المجموع الفرعي',
        shipping: 'الشحن',
        total: 'الإجمالي',
        placeOrder: 'تأكيد الطلب'
      },
      productDetails: {
        breadcrumbHome: 'الرئيسية',
        products: 'المنتجات',
        inStock: 'متوفر',
        outOfStock: 'غير متوفر',
        unitsAvailable: 'وحدات متاحة',
        keyFeatures: 'الميزات الرئيسية',
        addToCart: 'أضف للسلة',
        freeShippingNote: 'شحن مجاني للطلبات فوق 500$',
        support24: 'دعم العملاء 24/7',
        description: 'الوصف',
        specifications: 'المواصفات',
        reviews: 'التقييمات',
        productDescription: 'وصف المنتج',
        features: 'الميزات',
        installation: 'التركيب',
        technicalSpecifications: 'المواصفات التقنية',
        additionalTechnicalDetails: 'تفاصيل تقنية إضافية',
        customerReviews: 'مراجعات العملاء',
        writeReview: 'اكتب مراجعة',
        writeYourReview: 'اكتب مراجعتك',
        rating: 'التقييم',
        submitReview: 'إرسال المراجعة',
        cancel: 'إلغاء',
        noReviewsYet: 'لا توجد مراجعات بعد. كن أول من يراجع هذا المنتج!',
        loading: 'جارٍ تحميل تفاصيل المنتج...'
      }
    };

    // English
    this.translations.en = {
      common: {
        loading: 'Loading',
        required: 'Required',
        error: 'Error',
        success: 'Success',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        close: 'Close',
        confirm: 'Confirm',
        yes: 'Yes',
        no: 'No',
        search: 'Search',
        next: 'Next',
        previous: 'Previous',
        optional: 'Optional',
        and: 'and',
        email: 'Email',
        password: 'Password'
      },
      nav: {
        products: 'Products',
        categories: 'Categories',
        admin: 'Admin',
        account: 'Account',
        wishlist: 'Wishlist',
        cart: 'Cart',
        login: 'Login',
        logout: 'Logout',
        dashboard: 'Dashboard',
        myOrders: 'My Orders',
        profile: 'Profile',
        addresses: 'Addresses',
        adminPanel: 'Admin Panel',
        searchPlaceholder: 'Search security systems, cameras, alarms...'
      },
      admin: {
        dashboardTitle: 'Admin Dashboard',
        dashboardSubtitle: 'Manage site, products, users, orders and more',
        overview: 'Overview',
        manageUsers: 'Manage Users',
        manageProducts: 'Manage Products',
        manageCategories: 'Manage Categories',
        manageOrders: 'Manage Orders',
        manageBanners: 'Manage Banners',
        loginTitle: 'Admin Login',
        loginButton: 'Login',
        // Stats
        totalUsers: 'Total Users',
        totalProducts: 'Total Products',
        totalOrders: 'Total Orders',
        totalRevenue: 'Total Revenue',
        pendingOrders: 'Pending Orders',
        lowStockProducts: 'Low Stock Products',
        // Users
        users: 'Users',
        user: 'User',
        email: 'Email',
        name: 'Name',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
        active: 'Active',
        inactive: 'Inactive',
        admin: 'Admin',
        staff: 'Staff',
        customerRole: 'Customer',
        allRoles: 'All Roles',
        anyStatus: 'Any Status',
        filter: 'Filter',
        searchUsers: 'Search users...',
        deleteUser: 'Delete User',
        deleteUserConfirm: 'Are you sure you want to delete this user?',
        userDeleted: 'User deleted successfully',
        userUpdated: 'User updated successfully',
        // Categories
        categories: 'Categories',
        category: 'Category',
        addCategory: 'Add Category',
        editCategory: 'Edit Category',
        categoryName: 'Category Name',
        categorySlug: 'Slug',
        parentCategory: 'Parent Category',
        noParent: 'None (Top Level)',
        icon: 'Icon',
        image: 'Image',
        sortOrder: 'Sort Order',
        isActive: 'Active',
        saveCategory: 'Save Category',
        categoryAdded: 'Category added successfully',
        categoryUpdated: 'Category updated successfully',
        categoryDeleted: 'Category deleted successfully',
        deleteCategoryConfirm: 'Are you sure you want to delete this category?',
        // Banners
        banners: 'Banners',
        banner: 'Banner',
        addBanner: 'Add Banner',
        editBanner: 'Edit Banner',
        title: 'Title',
        imageUrl: 'Image URL',
        linkUrl: 'Link URL',
        position: 'Position',
        hero: 'Hero',
        sidebar: 'Sidebar',
        footer: 'Footer',
        startDate: 'Start Date',
        endDate: 'End Date',
        saveBanner: 'Save Banner',
        bannerAdded: 'Banner added successfully',
        bannerUpdated: 'Banner updated successfully',
        bannerDeleted: 'Banner deleted successfully',
        deleteBannerConfirm: 'Are you sure you want to delete this banner?',
        filterByPosition: 'Filter by Position',
        allPositions: 'All Positions',
        // Products
        products: 'Products',
        product: 'Product',
        addProduct: 'Add Product',
        editProduct: 'Edit Product',
        productName: 'Product Name',
        description: 'Description',
        price: 'Price',
        comparePrice: 'Compare Price',
        cost: 'Cost',
        sku: 'SKU',
        stock: 'Stock',
        lowStockThreshold: 'Low Stock Threshold',
        images: 'Images',
        specifications: 'Specifications',
        features: 'Features',
        saveProduct: 'Save Product',
        productAdded: 'Product added successfully',
        productUpdated: 'Product updated successfully',
        productDeleted: 'Product deleted successfully',
        deleteProductConfirm: 'Are you sure you want to delete this product?',
        // Orders
        orders: 'Orders',
        order: 'Order',
        orderNumber: 'Order Number',
        orderDate: 'Order Date',
        customer: 'Customer',
        items: 'Items',
        total: 'Total',
        paymentStatus: 'Payment Status',
        orderStatus: 'Order Status',
        pending: 'Pending',
        confirmed: 'Confirmed',
        processing: 'Processing',
        shipped: 'Shipped',
        delivered: 'Delivered',
        cancelled: 'Cancelled',
        paid: 'Paid',
        unpaid: 'Unpaid',
        refunded: 'Refunded',
        updateStatus: 'Update Status',
        orderUpdated: 'Order updated successfully',
        viewOrder: 'View Order',
        searchOrders: 'Search orders...',
        filterByStatus: 'Filter by Status',
        allStatuses: 'All Statuses',
        // Sales & Customers
        sales: 'Sales',
        sale: 'Sale',
        salesLedger: 'Sales Ledger',
        newSale: 'New Sale',
        addSale: 'Add Sale',
        salesHistory: 'Sales History',
        customers: 'Customers',
        customerName: 'Customer Name',
        customerPhone: 'Phone Number',
        customerEmail: 'Email',
        searchCustomer: 'Search customer...',
        newCustomer: 'New Customer',
        selectCustomer: 'Select Customer',
        serialNumber: 'Serial Number',
        searchBySerial: 'Search by serial number...',
        productNotFound: 'Product not found',
        addNewProduct: 'Add new product',
        quantity: 'Quantity',
        addItem: 'Add Item',
        removeItem: 'Remove Item',
        saleItems: 'Sale Items',
        totalAmount: 'Total Amount',
        paidAmount: 'Paid Amount',
        remainingAmount: 'Remaining Amount',
        payments: 'Payments',
        addPayment: 'Add Payment',
        paymentAmount: 'Payment Amount',
        paymentDate: 'Payment Date',
        paymentMethod: 'Payment Method',
        cash: 'Cash',
        card: 'Card',
        bank: 'Bank Transfer',
        returnItem: 'Return Item',
        returned: 'Returned',
        returnDate: 'Return Date',
        returnReason: 'Return Reason',
        uploadImages: 'Upload Images',
        saleDate: 'Sale Date',
        partial: 'Partial',
        saveSale: 'Save Sale',
        saleCreated: 'Sale created successfully',
        saleUpdated: 'Sale updated successfully',
        saleDeleted: 'Sale deleted successfully',
        deleteSaleConfirm: 'Are you sure you want to delete this sale?',
        searchSales: 'Search sales...',
        salesHistoryDesc: 'View and manage all sales',
        all: 'All',
        paidStatus: 'Paid',
        partialStatus: 'Partial',
        pendingStatus: 'Pending',
        totalSales: 'Total Sales',
        totalPaid: 'Total Paid',
        totalRemaining: 'Total Remaining',
        noSalesFound: 'No sales found',
        loadingSales: 'Loading sales...',
        saleDetails: 'Sale Details',
        customerInfo: 'Customer Information',
        phone: 'Phone',
        date: 'Date',
        noPaymentsYet: 'No payments yet',
        paymentFailed: 'Failed to add payment',
        returnFailed: 'Failed to return item',
        bankTransfer: 'Bank Transfer',
        // Common
        search: 'Search',
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        close: 'Close',
        loading: 'Loading...',
        noData: 'No data',
        error: 'An error occurred',
        success: 'Success',
        confirm: 'Confirm',
        back: 'Back'
      },
      home: {
        heroTitle: 'Protect What Matters',
        heroSubtitle: 'Advanced Security Solutions',
        heroDescription: 'Professional security systems for homes and businesses. 24/7 monitoring, smart integration, and expert installation.',
        shopNow: 'Shop Now',
        getQuote: 'Get Quote',
        happyCustomers: 'Happy Customers',
        uptime: 'Uptime',
        yearsExperience: 'Years Experience',
        browseByCategory: 'Browse By Category',
        categoriesDescription: 'Explore our comprehensive range of security products',
        feature1Title: '24/7 Security',
        feature1Desc: 'Round-the-clock protection for your property',
        feature2Title: 'Professional Support',
        feature2Desc: 'Expert installation and maintenance',
        feature3Title: 'Premium Quality',
        feature3Desc: 'Industry-leading security products',
        feature4Title: 'Fast Delivery',
        feature4Desc: 'Quick and secure shipping nationwide',
        featuredProducts: 'Featured Products',
        featuredDescription: 'Top-rated security solutions trusted by thousands',
        viewAllProducts: 'View All Products',
        ctaTitle: 'Need Help Choosing the Right Security System?',
        ctaDescription: 'Our security experts are here to help you find the perfect solution for your needs.',
        talkToExpert: 'Talk to an Expert',
        callNow: 'Call Now'
      },
      products: {
        title: 'Security Products',
        subtitle: 'Professional-grade security systems and equipment',
        searchPlaceholder: 'Search products...',
        filters: 'Filters',
        clearAll: 'Clear All',
        clearFilters: 'Clear Filters',
        category: 'Category',
        allCategories: 'All Categories',
        priceRange: 'Price Range',
        min: 'Min',
        max: 'Max',
        availability: 'Availability',
        allProducts: 'All Products',
        inStock: 'In Stock',
        inStockLabel: 'in stock',
        outOfStock: 'Out of Stock',
        lowStock: 'Low Stock',
        quickView: 'Quick View',
        addToCart: 'Add to Cart',
        productsFound: 'Products Found',
        page: 'Page',
        of: 'of',
        noProductsFound: 'No Products Found',
        tryAdjusting: 'Try adjusting your filters or search terms'
      },
      account: {
        welcome: 'Welcome',
        totalOrders: 'Total Orders',
        pendingOrders: 'Pending Orders',
        wishlistItems: 'Wishlist Items',
        savedAddresses: 'Saved Addresses',
        recentOrders: 'Recent Orders',
        viewAll: 'View All',
        orderNumber: 'Order',
        date: 'Date',
        status: 'Status',
        total: 'Total',
        viewDetails: 'View Details'
      },
      categoriesPage: {
        title: 'Product Categories',
        subtitle: 'Explore our comprehensive range of security solutions',
        categoriesLabel: 'Categories',
        productsLabel: 'Products',
        loadingCategories: 'Loading categories',
        exploreProducts: 'Explore Products',
        needHelp: 'Need Help Choosing?',
        helpDescription: 'Our security experts are here to help you find the perfect solution for your needs',
        contactUs: 'Contact Us',
        requestQuote: 'Request Quote'
      },
      footer: {
        brandDescription: 'Your trusted partner in advanced security solutions. Protecting what matters most with cutting-edge technology and reliable service.',
        company: 'Company',
        aboutUs: 'About Us',
        careers: 'Careers',
        blog: 'Blog',
        pressKit: 'Press Kit',
        support: 'Support',
        helpCenter: 'Help Center',
        contactUs: 'Contact Us',
        faq: 'FAQ',
        shipping: 'Shipping',
        returns: 'Returns',
        legal: 'Legal',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        cookiePolicy: 'Cookie Policy',
        newsletter: 'Subscribe to Our Newsletter',
        newsletterDesc: 'Get the latest updates on security products and exclusive offers.',
        emailPlaceholder: 'Enter your email address',
        subscribe: 'Subscribe',
        allRightsReserved: 'All rights reserved.',
        weAccept: 'We Accept:'
      },
      login: {
        welcomeBack: 'Welcome Back',
        signInSubtitle: 'Sign in to your account to continue',
        professionalSystems: 'Professional Grade Systems',
        monitoring247: '24/7 Monitoring Support',
        expertInstallation: 'Expert Installation',
        email: 'Email Address',
        emailPlaceholder: 'Enter your email',
        emailRequired: 'Email is required',
        emailInvalid: 'Please enter a valid email',
        password: 'Password',
        passwordPlaceholder: 'Enter your password',
        passwordRequired: 'Password is required',
        passwordMinLength: 'Password must be at least 6 characters',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot Password?',
        signIn: 'Sign In',
        signingIn: 'Signing in...',
        or: 'or',
        continueWithGoogle: 'Continue with Google',
        continueWithFacebook: 'Continue with Facebook',
        continueWithApple: 'Continue with Apple',
        noAccount: "Don't have an account?",
        createAccount: 'Create Account'
      },
      register: {
        createAccount: 'Create Account',
        createAccountSubtitle: 'Create your account and start securing what matters most',
        joinThousands: 'Join thousands of customers who trust us',
        firstName: 'First Name',
        firstNamePlaceholder: 'Enter your first name',
        firstNameRequired: 'First name is required',
        nameMinLength: 'At least 2 characters',
        lastName: 'Last Name',
        lastNamePlaceholder: 'Enter your last name',
        lastNameRequired: 'Last name is required',
        phoneNumber: 'Phone Number',
        phonePlaceholder: 'Enter your phone number',
        phoneInvalid: 'Please enter a valid phone number',
        company: 'Company',
        companyPlaceholder: 'Your company name',
        confirmPassword: 'Confirm Password',
        confirmPasswordPlaceholder: 'Re-enter your password',
        confirmPasswordRequired: 'Please confirm your password',
        passwordMismatch: 'Passwords do not match',
        agreeToTerms: 'I agree to the',
        termsConditions: 'Terms & Conditions',
        privacyPolicy: 'Privacy Policy',
        termsRequired: 'You must agree to the terms and conditions',
        creatingAccount: 'Creating account...',
        alreadyHaveAccount: 'Already have an account?'
      },
      accountDash: {
        myAccount: 'My Account',
        overview: 'Overview',
        orders: 'Orders',
        addresses: 'Addresses',
        profile: 'Profile',
        viewAll: 'View all',
        manage: 'Manage',
        viewAllOrders: 'View All Orders',
        recentOrders: 'Recent Orders',
        noOrders: 'No orders yet',
        startShopping: 'Start Shopping',
        order: 'Order',
        items: 'items',
        view: 'View',
        quickActions: 'Quick Actions',
        updateProfile: 'Update Profile',
        manageAddresses: 'Manage Addresses',
        orderHistory: 'Order History',
        accountSettings: 'Account Settings'
      },
      accountProfile: {
        profile: 'Profile',
        subtitle: 'Manage your account information and security settings',
        personalInfo: 'Personal Information',
        updatePersonalInfo: 'Update your personal information',
        securitySettings: 'Security Settings',
        updatePasswordDesc: 'Update your password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        changePassword: 'Change Password',
        updating: 'Updating...',
        saveChanges: 'Save Changes',
        cancel: 'Cancel'
      },
      accountOrders: {
        title: 'My Orders',
        subtitle: 'Track and manage your order history',
        status: 'Status',
        dateRange: 'Date Range',
        allOrders: 'All Orders',
        pending: 'Pending',
        confirmed: 'Confirmed',
        shipped: 'Shipped',
        delivered: 'Delivered',
        cancelled: 'Cancelled',
        allTime: 'All Time',
        last30Days: 'Last 30 Days',
        last90Days: 'Last 90 Days',
        thisYear: 'This Year',
        search: 'Search',
        searchPlaceholder: 'Order ID, status, tracking...',
        loading: 'Loading orders...',
        orderId: 'Order ID',
        date: 'Date',
        items: 'Items',
        total: 'Total',
        statusLabel: 'Status',
        payment: 'Payment',
        actions: 'Actions',
        view: 'View',
        noOrdersFound: 'No orders found',
        tryAdjustFilters: 'Try adjusting your filters',
        noOrdersYet: "You haven't placed any orders yet",
        startShopping: 'Start Shopping',
        details: 'Order Details',
        paymentStatus: 'Payment',
        tracking: 'Tracking',
        itemsHeader: 'Items',
        shippingAddress: 'Shipping Address',
        orderSummary: 'Order Summary',
        subtotal: 'Subtotal',
        shipping: 'Shipping',
        tax: 'Tax',
        totalLabel: 'Total',
        notes: 'Notes',
        qty: 'Qty'
      },
      accountAddresses: {
        title: 'Shipping Addresses',
        subtitle: 'Manage your saved addresses for faster checkout',
        addNewAddress: 'Add New Address',
        loading: 'Loading addresses...',
        editAddress: 'Edit Address',
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        streetAddress: 'Street Address',
        apartment: 'Apartment, Suite, etc.',
        city: 'City',
        state: 'State / Province',
        postalCode: 'Postal Code',
        country: 'Country',
        setAsDefault: 'Set as default address',
        isDefault: 'Default',
        noAddressesSaved: 'No addresses saved',
        addAddressCta: 'Add your first shipping address to get started',
        addAddress: 'Add Address',
        saveAddress: 'Save Address',
        updateAddress: 'Update Address',
        saving: 'Saving...',
        cancel: 'Cancel',
        defaultUpdated: 'Default address updated!',
        deleteConfirm: 'Are you sure you want to delete this address?',
        deleteSuccess: 'Address deleted successfully!',
        addSuccess: 'Address added successfully!',
        updateSuccess: 'Address updated successfully!',
        loadError: 'Failed to load addresses',
        updateError: 'Failed to update address',
        addError: 'Failed to add address',
        deleteError: 'Failed to delete address'
      },
      checkout: {
        title: 'Checkout',
        subtitle: 'Secure checkout in three simple steps',
        step1: 'Shipping',
        step2: 'Payment',
        step3: 'Review',
        shippingInformation: 'Shipping Information',
        fullName: 'Full Name',
        email: 'Email',
        phone: 'Phone',
        address1: 'Address 1',
        address2: 'Address 2',
        city: 'City',
        state: 'State',
        zip: 'ZIP',
        country: 'Country',
        continueToPayment: 'Continue to Payment',
        payment: 'Payment',
        methodCard: 'Credit/Debit Card',
        methodCOD: 'Cash on Delivery',
        cardNumber: 'Card Number',
        nameOnCard: 'Name on Card',
        expiry: 'Expiry',
        cvc: 'CVC',
        back: 'Back',
        reviewOrder: 'Review Order',
        reviewYourOrder: 'Review Your Order',
        orderSummary: 'Order Summary',
        items: 'Items',
        subtotal: 'Subtotal',
        shipping: 'Shipping',
        total: 'Total',
        placeOrder: 'Place Order'
      },
      productDetails: {
        breadcrumbHome: 'Home',
        products: 'Products',
        inStock: 'In Stock',
        outOfStock: 'Out of Stock',
        unitsAvailable: 'units available',
        keyFeatures: 'Key Features',
        addToCart: 'Add to Cart',
        freeShippingNote: 'Free Shipping on Orders Over $500',
        support24: '24/7 Customer Support',
        description: 'Description',
        specifications: 'Specifications',
        reviews: 'Reviews',
        productDescription: 'Product Description',
        features: 'Features',
        installation: 'Installation',
        technicalSpecifications: 'Technical Specifications',
        additionalTechnicalDetails: 'Additional Technical Details',
        customerReviews: 'Customer Reviews',
        writeReview: 'Write a Review',
        writeYourReview: 'Write Your Review',
        rating: 'Rating',
        submitReview: 'Submit Review',
        cancel: 'Cancel',
        noReviewsYet: 'No reviews yet. Be the first to review this product!',
        loading: 'Loading product details...'
      }
    };
  }

  toggleLanguage(): void {
    this.currentLanguage.update((current) => (current === 'ar' ? 'en' : 'ar'));
  }

  setLanguage(lang: Language): void {
    this.currentLanguage.set(lang);
  }

  isArabic(): boolean {
    return this.currentLanguage() === 'ar';
  }

  isRTL(): boolean {
    return this.currentLanguage() === 'ar';
  }

  // Get translation by key (supports nested keys with dot notation)
  translate(key: string): string {
    const keys = key.split('.');
    const currentLang = this.currentLanguage(); // Get current value from signal
    let value: any = this.translations[currentLang];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        console.warn(`Translation key not found: ${key} for language: ${currentLang}`);
        return key;
      }
    }
    return typeof value === 'string' ? value : key;
  }

  // Shorthand for translate
  t(key: string): string {
    return this.translate(key);
  }
}
